# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: execbeat
before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    package_name: execbeat_3.3.2_pre
    file_name_template: "execbeat_3.3.3_pre{{ .Os }}_{{ .Arch }}"
    maintainer: Lavish Jain <lavishrjain1997@gmail.com>
    formats:
      - deb
      - rpm
